// src/features/posts/postsData.js
export const postsData = [
  {
    id: 1,
    username: "Shinchan",
    profile: "/instaprofile.jpg",
    time: "Suggested for you • 2d",
    type: "image",
    content: "/shinchanpost1.jpg",
    likes: 100,
    liked: false,
    saved: false,
    caption: "When something makes my heart sparkle ✨",
  },
  {
    id: 2,
    username: "Tom & Jerry",
    profile: "/tomprofile.jpg",
    time: "Suggested for you • 3d",
    type: "image",
    content: "/tompost.jpg",
    likes: 5,
    liked: false,
    saved: false,
    caption:
      "Sometimes love looks a little dramatic a little tight, and a little chaotic too. But deep down it is just pure affection in disguise. Even the toughest hearts melt for their favorite person💞...more",
  },
  {
    id: 3,
    username: "Motu Patlu",
    profile: "/motupatluprofile.jpg",
    time: "Suggested for you • 1d",
    type: "image",
    content: "/motupatlupost.webp",
    likes: 0,
    liked: false,
    saved: false,
    caption:
      "These two may argue every single day, but their bond is stronger than all their fights. One plans, the other panics — yet they never leave each other’s side. Through every crazy idea and funny disaster, they stand together. Because some friendships are loud, dramatic…but forever.💛🔥...more",
  },
  {
    id: 4,
    username: "Shinchan",
    profile: "/instaprofile.jpg",
    time: "Suggested for you • 5d",
    type: "video",
    content: "/myvideo.mp4",
    likes: 10,
    liked: false,
    saved: false,
    caption: "Thalaivan Dance...🔥",
  },
  {
    id: 5,
    username: "Doraemon",
    profile: "/doraemonprofile.jpg",
    time: "Suggested for you • 1d",
    type: "image",
    content: "/doraemonpost.jpg",
    likes: 100,
    liked: false,
    saved: false,
    caption:
      "This cartoon shows the beautiful friendship between Doraemon and his friends, filled with fun, adventure, and life lessons.Along with Shizuka, Gian, and Suneo, they create unforgettable memories together. It’s a heartwarming story that teaches the value of friendship, courage, and kindness.💙...more",
  },
];
